#
# Google Cloud Builder CI configuration
#

options:

    substitution_option: 'ALLOW_LOOSE'

substitutions:
      
    _BUILD_BASE_DIR_PACKAGE: '/workspace/package'    
    _BUILD_BASE_DIR_DEST: '/workspace/build'
    _BUILD_BASE_DIR_DATA: '/workspace/data'
    
    _PACKAGE_BASE_DIR_REPO_CONTENT: 'content/repo'
   
steps:

# SETUP WORKSPACE DIRECTORIES

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}
    mkdir -p ${_BUILD_BASE_DIR_DEST}
    mkdir -p ${_BUILD_BASE_DIR_DATA}


# SETUP THE CONTENT FOR THE BUILD

# Pull the content (Use https for now, no keys needed)
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '$_REPO_URL_HTTPS_CONTENT'
  - '${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}'

# Save the last commit sha value in a workspace file, accessable by future steps
#- name: 'gcr.io/cloud-builders/git'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    git -C /workspace/content rev-parse HEAD > /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt
#    echo "Displaying value of: /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt"
#    cat /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt

# BUILD SITE PACKAGE

- name: '$_SITE_BUILD_CONTAINER'
  args:
  - 'a_testing_variable_value'
  - 'another_variable_for_testing'
  
- name: '$_SITE_BUILD_CONTAINER'
  env:
  - 'CONTENT_DIR=${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}/$_DIR_NAME_CONTENT'
  #- 'BUILD_DIR=${_BUILD_BASE_DIR_DEST}/'

- name: '$_SITE_BUILD_CONTAINER'
  env:
  #- 'CONTENT_DIR=${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}/$_DIR_NAME_CONTENT'
  - 'BUILD_DIR=${_BUILD_BASE_DIR_DEST}'

- name: '$_SITE_BUILD_CONTAINER'
  env:
  - 'CONTENT_DIR=${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}/$_DIR_NAME_CONTENT'
  - 'BUILD_DIR=${_BUILD_BASE_DIR_DEST}'  
  
