#
# Google Cloud Builder CI configuration
#

options:

    substitution_option: 'ALLOW_LOOSE'

substitutions:
      
    _BUILD_BASE_DIR_PACKAGE: '/workspace/package'    
    _BUILD_BASE_DIR_BUILD: '/workspace/build'
    _BUILD_BASE_DIR_DIST: '/workspace/dist'
    _BUILD_BASE_DIR_DATA: '/workspace/data'
    
    _PACKAGE_BASE_DIR_REPO_CONTENT: 'content/repo'
   
steps:

# SETUP WORKSPACE DIRECTORIES

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}
    mkdir -p ${_BUILD_BASE_DIR_BUILD}
    mkdir -p ${_BUILD_BASE_DIR_DATA}
    
    mkdir -p /workspace/content


# SETUP THE CONTENT FOR THE BUILD

# Pull the content (Use https for now, no keys needed)
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '${_REPO_URL_HTTPS_CONTENT}'
  - '${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}'

# Save the last commit sha value in a workspace file, accessable by future steps
#- name: 'gcr.io/cloud-builders/git'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    git -C /workspace/content rev-parse HEAD > /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt
#    echo "Displaying value of: /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt"
#    cat /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt


#####################################################
######### CREATE PRELOAD CONTAINER FOR KEYS #########
#####################################################
# SETUP KEYS FOR GIT DIST REPO

# Copy the encrypted file from GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '$_DIST_GIT_SSH_KEY_GCS_URL', '/workspace/tmp/encrypted_key/id_rsa_dist.enc']
  volumes:
  - name: 'ssh'
    path: '/root/.ssh'
    
# Decrypt files in the persisted volume
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=/workspace/tmp/encrypted_key/id_rsa_dist.enc
  - --plaintext-file=/root/.ssh/id_rsa_dist
  - --location=global
  - --keyring=$_DIST_GIT_SSH_KEY_KMS_KEYRING
  - --key=$_DIST_GIT_SSH_KEY_KMS_KEY
  volumes:
  - name: 'ssh'
    path: '/root/.ssh'

# Add GitHub to known hosts and set up git with key and domain
- name: 'gcr.io/cloud-builders/git' 
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    rm -f /workspace/tmp/encrypted_key/id_rsa_dist.enc
    rm -rf /workspace/tmp
    \
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    \
    cat <<EOF >/root/.ssh/config
    SendEnv SSHPASS
    Hostname github.com
    User git
    IdentityFile /root/.ssh/id_rsa_dist
    EOF
    \
    chmod 600 /root/.ssh/* 
    chmod 644 /root/.ssh/config
    \
    #ssh -xvvv git@github.com
  volumes:
  - name: 'ssh'
    path: /root/.ssh





#####################################################
######## CREATE PRELOAD CONTAINER DIST PUSH #########
#####################################################

# SETUP DIST GIT AND PUSH THE PACKAGE

# Clone the distribution repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '${_REPO_URL_GIT_DIST}'
  - '${_BUILD_BASE_DIR_DIST}'
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Setup credentials for local dist repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '${_BUILD_BASE_DIR_DIST}'
  - 'config'
  - 'user.name'
  - '$_GIT_COMMITTER_NAME'

- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '${_BUILD_BASE_DIR_DIST}'
  - 'config'
  - 'user.email'
  - '$_GIT_COMMITTER_EMAIL'

# Empty the cloned dist directory ready to add the new build
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir /workspace/tmp
    mv ${_BUILD_BASE_DIR_DIST}/.git /workspace/tmp/.git
    \
    # clean out prepared git dist dir
    rm -rf ${_BUILD_BASE_DIR_DIST}*
    # put git back
    mv /workspace/tmp/.git ${_BUILD_BASE_DIR_DIST}/.git
    rmdir /workspace/tmp

# Stage added and deleted files to git
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '${_BUILD_BASE_DIR_DIST}'
  - 'add'
  - '--all'

# BUILD SITE PACKAGE

- name: '$_SITE_BUILD_CONTAINER'
  env:
  - 'CONTENT_DIR=${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}/$_DIR_NAME_CONTENT'
  #- 'BUILD_DIR=${_BUILD_BASE_DIR_BUILD}'  
  - 'BUILD_DIR=${_BUILD_BASE_DIR_DEST}'  
  
#####################################################
################### TESTING ONLY ####################
#####################################################
# Check the build is in the right place
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find  ${_BUILD_BASE_DIR_DEST}/.

#####################################################
################### TESTING ONLY ####################
#####################################################
# Create a unique file so git always has something new to deploy
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    \
    cat <<EOF >${_BUILD_BASE_DIR_DEST}/BUILD${BUILD_ID}-${RANDOM}
    This is a unique file for build ${BUILD_ID} in the ${PROJECT_ID} project.
    EOF
 
# Stage added and deleted files to git
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '${_BUILD_BASE_DIR_DIST}'
  - 'add'
  - '--all'

# Display status (for testing)
#- name: 'gcr.io/cloud-builders/git'
#  args:
#  - '-C'
#  - '${_BUILD_BASE_DIR_DIST}'
#  - 'status'

# Commit the files to local
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '${_BUILD_BASE_DIR_DIST}'
  - 'commit'
  - '-m'
  - 'Commiting files to dist for ${BUILD_ID}'

# Display status (for testing)
#- name: 'gcr.io/cloud-builders/git'
#  args:
#  - '-C'
#  - '${_BUILD_BASE_DIR_DIST}'
#  - 'status'

# Push to remote
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '${_BUILD_BASE_DIR_DIST}'
  - 'push'
  - '--force'
  - '--set-upstream'
  - 'origin'
  - 'master'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
