# pull the latest content

# build using the prepared implimentation image

# push to distribution repo

# deploy (if needed)


#
# Google Cloud Builder CI configuration
#

steps:

# GET THE CONTENT REPO CREDENTIALS and SETUP FROM THE BUILDER IMAGE


# SETUP WORKSPACE DIRECTORIES

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p /workspace/content
    mkdir -p /workspace/build
    mkdir -p /workspace/dist


# PULL CONTENT FROM CONTENT REPO (Use https for now, no keys needed)

- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '/workspace/content'
  - 'clone'
  - '$_CONTENT_GIT_REPO_HTTP_LOCATION'
  - '/repo'


# SET LAST COMMIT VARIABLE

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
  - eval local_CONTENT_GIT_COMMIT_SHA=$(git -C /workspace/content/repo rev-parse HEAD)"
  - git -C /workspace/content/repo rev-parse HEAD | cat > workspace/data/CONTENT_GIT_COMMIT_SHA.txt


# BUILD SITE PACKAGE

- name: '$_SITE_BUILD_CONTAINER'
  args:
  # feed in arguments i) build location path, ii) content path iii) repo base folder
  - '/workspace/build'
  - '/workspace/content/repo'
  - '/content'


# SETUP KEYS FOR GIT PUSH TO DIST REPO

# Copy the encrypted file from GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '$_DIST_GIT_SSH_KEY_GCS_URL', '/workspace/tmp/encrypted_key/id_rsa_dist.enc']
  volumes:
  - name: 'ssh'
    path: '/root/.ssh'
    
# Decrypt files in the persisted volume
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=/workspace/tmp/encrypted_key/id_rsa_dist.enc
  - --plaintext-file=/root/.ssh/id_rsa_dist
  - --location=global
  - --keyring=$_DIST_GIT_SSH_KEY_KMS_KEYRING
  - --key=$_DIST_GIT_SSH_KEY_KMS_KEY
  volumes:
  - name: 'ssh'
    path: '/root/.ssh'

# Add GitHub to known hosts and set up git with key and domain
- name: 'gcr.io/cloud-builders/git' 
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    rm -rf /workspace/tmp
    \
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    \
    cat <<EOF >/root/.ssh/config
    SendEnv SSHPASS
    Hostname github.com
    User git
    IdentityFile /root/.ssh/id_rsa_dist
    EOF
    \
    chmod 600 /root/.ssh/* 
    chmod 644 /root/.ssh/config
    \
    #ssh -xvvv git@github.com
  volumes:
  - name: 'ssh'
    path: /root/.ssh


# SETUP GIT FOR DIST

# Clone the distribution repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '/workspace/dist'
  - 'clone'
  - '$_DIST_GIT_REPO_LOCATION_SSH'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
