# pull the latest content

# build using the prepared implimentation image

# push to distribution repo

# deploy (if needed)


#
# Google Cloud Builder CI configuration
#

steps:

# GET THE CONTENT REPO CREDENTIALS and SETUP FROM THE BUILDER IMAGE


# PULL CONTENT FROM CONTENT REPO (Use https for now, no keys needed)

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir /workspace/content

- name: 'gcr.io/cloud-builders/git'
  args:
  - '-C'
  - '/workspace/content'
  - 'clone'
  - '$_CONTENT_GIT_REPO_HTTP_LOCATION'
  - '/repo'

# SET LAST COMMIT VARIABLE

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
  - eval _CONTENT_GIT_COMMIT_SHA=$(git -C /workspace/content/repo rev-parse HEAD)"
