# pull the latest content

# build using the prepared implimentation image

# push to distribution repo

# deploy (if needed)


#
# Google Cloud Builder CI configuration
#

options:

    substitution_option: 'ALLOW_LOOSE'


steps:

# GET THE CONTENT REPO CREDENTIALS and SETUP FROM THE BUILDER IMAGE


# SETUP WORKSPACE DIRECTORIES

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p /workspace/content
    mkdir -p /workspace/build
    mkdir -p /workspace/dist
    mkdir -p /workspace/data


# SETUP THE CONTENT FOR THE BUILD

# Pull the content (Use https for now, no keys needed)
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '$_CONTENT_GIT_REPO_HTTP_LOCATION'
  - '/workspace/content/repo'

#- name: 'gcr.io/cloud-builders/git'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    find /workspace/content/repo type -d 

# Save the last commit sha value in a workspace file, accessable by future steps
#- name: 'gcr.io/cloud-builders/git'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    git -C /workspace/content rev-parse HEAD > /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt
#    echo "Displaying value of: /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt"
#    cat /workspace/data/CONTENT_LATEST_COMMIT_SHA.txt

# BUILD SITE PACKAGE

# Test run the site specific build container (without arguments should build locally with test content and paths)
- name: '$_SITE_BUILD_CONTAINER'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    #echo "PWD:"
    #pwd
    #echo "LS: ROOT"
    #ls /
    #echo "LS: WORKSPACE"
    #ls /workspace

- name: '$_SITE_BUILD_CONTAINER'
  args:
  - 'a_testing_variable_value'
  - 'another_variable_for_testing'

- name: '$_SITE_BUILD_CONTAINER'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    ls /workspace
